package com.example.demo;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.By;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.List;

@Component
public class WebCrawler {

    @Autowired
    private GeminiClient geminiClient;

    @Autowired
    private FirebaseService firebaseService;

    private final List<String> urlsToCrawl = Arrays.asList(
    "https://www.fonts.googleapis.com",
    "https://www.facebook.com",
    "https://www.twitter.com",
    "https://www.google.com",
    "https://www.youtube.com",
    "https://www.s.w.org",
    "https://www.instagram.com",
    "https://www.googletagmanager.com",
    "https://www.linkedin.com",
    "https://www.ajax.googleapis.com",
    "https://www.plus.google.com",
    "https://www.gmpg.org",
    "https://www.pinterest.com",
    "https://www.fonts.gstatic.com",
    "https://www.wordpress.org",
    "https://www.en.wikipedia.org",
    "https://www.youtu.be",
    "https://www.maps.google.com",
    "https://www.itunes.apple.com",
    "https://www.github.com",
    "https://www.bit.ly",
    "https://www.play.google.com",
    "https://www.goo.gl",
    "https://www.docs.google.com",
    "https://www.cdnjs.cloudflare.com",
    "https://www.vimeo.com",
    "https://www.support.google.com",
    "https://www.google-analytics.com",
    "https://www.maps.googleapis.com",
    "https://www.flickr.com",
    "https://www.vk.com",
    "https://www.t.co",
    "https://www.reddit.com",
    "https://www.amazon.com",
    "https://www.medium.com",
    "https://www.sites.google.com",
    "https://www.drive.google.com",
    "https://www.creativecommons.org",
    "https://www.microsoft.com",
    "https://www.developers.google.com",
    "https://www.adobe.com",
    "https://www.soundcloud.com",
    "https://www.theguardian.com",
    "https://www.apis.google.com",
    "https://www.ec.europa.eu",
    "https://www.lh3.googleusercontent.com",
    "https://www.chrome.google.com",
    "https://www.cloudflare.com",
    "https://www.nytimes.com",
    "https://www.maxcdn.bootstrapcdn.com",
    "https://www.support.microsoft.com",
    "https://www.blogger.com",
    "https://www.forbes.com",
    "https://www.s3.amazonaws.com",
    "https://www.code.jquery.com",
    "https://www.dropbox.com",
    "https://www.translate.google.com",
    "https://www.paypal.com",
    "https://www.apps.apple.com",
    "https://www.tinyurl.com",
    "https://www.etsy.com",
    "https://www.theatlantic.com",
    "https://www.m.facebook.com",
    "https://www.archive.org",
    "https://www.amzn.to",
    "https://www.cnn.com",
    "https://www.policies.google.com",
    "https://www.commons.wikimedia.org",
    "https://www.issuu.com",
    "https://www.i.imgur.com",
    "https://www.wordpress.com",
    "https://www.wp.me",
    "https://www.businessinsider.com",
    "https://www.yelp.com",
    "https://www.mail.google.com",
    "https://www.support.apple.com",
    "https://www.t.me",
    "https://www.apple.com",
    "https://www.washingtonpost.com",
    "https://www.bbc.com",
    "https://www.gstatic.com",
    "https://www.imgur.com",
    "https://www.amazon.de",
    "https://www.bbc.co.uk",
    "https://www.googleads.g.doubleclick.net",
    "https://www.mozilla.org",
    "https://www.eventbrite.com",
    "https://www.slideshare.net",
    "https://www.w3.org",
    "https://www.forms.gle",
    "https://www.platform.twitter.com",
    "https://www.accounts.google.com",
    "https://www.telegraph.co.uk",
    "https://www.messenger.com",
    "https://www.web.archive.org",
    "https://www.secure.gravatar.com",
    "https://www.usatoday.com",
    "https://www.huffingtonpost.com",
    "https://www.stackoverflow.com",
    "https://www.fb.com",
    "https://www.npr.org",
    "https://www.techcrunch.com",
    "https://www.wired.com",
    "https://www.eepurl.com",
    "https://www.reuters.com",
    "https://www.arxiv.org",
    "https://www.i0.wp.com",
    "https://www.finance.yahoo.com",
    "https://www.player.vimeo.com",
    "https://www.amazon.fr",
    "https://www.developer.mozilla.org",
    "https://www.tumblr.com",
    "https://www.cnbc.com",
    "https://www.booking.com",
    "https://www.zoom.us",
    "https://www.tools.google.com",
    "https://www.wa.me",
    "https://www.paypal.me",
    "https://www.slack.com",
    "https://www.adwords.google.com",
    "https://www.independent.co.uk",
    "https://www.discord.gg",
    "https://www.open.spotify.com",
    "https://www.tripadvisor.com",
    "https://www.gsuite.google.com",
    "https://www.behance.net",
    "https://www.thinkwithgoogle.com",
    "https://www.who.int",
    "https://www.cloud.google.com",
    "https://www.calendar.google.com",
    "https://www.ibm.com",
    "https://www.analytics.google.com",
    "https://www.lh5.googleusercontent.com",
    "https://www.docs.microsoft.com",
    "https://www.groups.google.com",
    "https://www.mixcloud.com",
    "https://www.google.co.in",
    "https://www.latimes.com",
    "https://www.gist.github.com",
    "https://www.download.macromedia.com",
    "https://www.dailymail.co.uk",
    "https://www.myaccount.google.com",
    "https://www.line.me",
    "https://www.unsplash.com",
    "https://www.addons.mozilla.org",
    "https://www.msdn.microsoft.com",
    "https://www.storage.googleapis.com",
    "https://www.pagead2.googlesyndication.com",
    "https://www.cdn.jsdelivr.net",
    "https://www.g.co",
    "https://www.meetup.com",
    "https://www.bloomberg.com",
    "https://www.books.google.com",
    "https://www.vox.com",
    "https://www.imdb.com",
    "https://www.arstechnica.com",
    "https://www.support.mozilla.org",
    "https://www.amazon.co.uk",
    "https://www.statista.com",
    "https://www.google.ca",
    "https://www.nbcnews.com",
    "https://www.steemit.com",
    "https://www.upload.wikimedia.org",
    "https://www.aws.amazon.com",
    "https://www.amazon.co.jp",
    "https://www.w3schools.com",
    "https://www.weibo.com",
    "https://www.twitch.tv",
    "https://www.moz.com",
    "https://www.drupal.org",
    "https://www.nypost.com",
    "https://www.fr.wikipedia.org",
    "https://www.ebay.com",
    "https://www.sourceforge.net",
    "https://www.godaddy.com",
    "https://www.ncbi.nlm.nih.gov",
    "https://www.wsj.com",
    "https://www.thenextweb.com",
    "https://www.cdc.gov",
    "https://www.photos.google.com",
    "https://www.trends.google.com",
    "https://www.opera.com",
    "https://www.ftc.gov",
    "https://www.j.mp",
    "https://www.about.me",
    "https://www.gov.uk",
    "https://www.i.ytimg.com",
    "https://www.squareup.com",
    "https://www.google.co.uk",
    "https://www.buzzfeed.com",
    "https://www.developer.apple.com",
    "https://www.pixabay.com",
    "https://www.quora.com",
    "https://www.cnet.com",
    "https://www.google.com.au",
    "https://www.myspace.com",
    "https://www.theglobeandmail.com",
    "https://www.shopify.com",
    "https://www.whitehouse.gov",
    "https://www.marketingplatform.google.com",
    "https://www.kickstarter.com",
    "https://www.freelancer.com",
    "https://www.evernote.com",
    "https://www.gmail.com",
    "https://www.static.wixstatic.com",
    "https://www.fortune.com",
    "https://www.wix.com",
    "https://www.dailymotion.com",
    "https://www.goodreads.com",
    "https://www.podcasts.google.com",
    "https://www.google.co.jp",
    "https://www.support.cloudflare.com",
    "https://www.surveymonkey.com",
    "https://www.cbsnews.com",
    "https://www.entrepreneur.com",
    "https://www.bing.com",
    "https://www.engadget.com",
    "https://www.lh4.googleusercontent.com",
    "https://www.tandfonline.com",
    "https://www.cargocollective.com",
    "https://www.join.slack.com",
    "https://www.api.whatsapp.com",
    "https://www.shutterstock.com",
    "https://www.pbs.twimg.com",
    "https://www.blog.google",
    "https://www.ads.google.com",
    "https://www.time.com",
    "https://www.lifehacker.com",
    "https://www.patreon.com",
    "https://www.scribd.com",
    "https://www.lh6.googleusercontent.com",
    "https://www.feeds.feedburner.com",
    "https://www.trello.com",
    "https://www.ted.com",
    "https://www.helpx.adobe.com",
    "https://www.researchgate.net",
    "https://www.fda.gov",
    "https://www.instructables.com",
    "https://www.google.de",
    "https://www.digitalocean.com",
    "https://www.dribbble.com",
    "https://www.ssl.gstatic.com",
    "https://www.variety.com",
    "https://www.indiegogo.com",
    "https://www.salesforce.com",
    "https://www.uk.linkedin.com",
    "https://www.nasa.gov",
    "https://www.codepen.io",
    "https://www.newyorker.com",
    "https://www.abcnews.go.com",
    "https://www.snapchat.com",
    "https://www.googleadservices.com",
    "https://www.sciencedirect.com",
    "https://www.ft.com",
    "https://www.nature.com",
    "https://www.gofundme.com",
    "https://www.500px.com",
    "https://www.qz.com",
    "https://www.dl.dropboxusercontent.com",
    "https://www.store.steampowered.com",
    "https://www.webmasters.googleblog.com",
    "https://www.podcasts.apple.com",
    "https://www.oracle.com",
    "https://www.m.youtube.com",
    "https://www.gartner.com",
    "https://www.web.facebook.com",
    "https://www.blogs.msdn.com",
    "https://www.mailchi.mp",
    "https://www.digg.com",
    "https://www.skype.com",
    "https://www.periscope.tv",
    "https://www.google.com.br",
    "https://www.googleblog.blogspot.com",
    "https://www.de.wikipedia.org",
    "https://www.search.google.com",
    "https://www.npmjs.com",
    "https://www.motherboard.vice.com",
    "https://www.aboutads.info",
    "https://www.pexels.com",
    "https://www.sxsw.com",
    "https://www.fiverr.com",
    "https://www.code.google.com",
    "https://www.cbc.ca",
    "https://www.venturebeat.com",
    "https://www.hangouts.google.com",
    "https://www.mashable.com",
    "https://www.upwork.com",
    "https://www.bitly.com",
    "https://www.music.apple.com",
    "https://www.loc.gov",
    "https://www.news.google.com",
    "https://www.spotify.com",
    "https://www.netflix.com",
    "https://www.hbr.org",
    "https://www.pbs.org",
    "https://www.stumbleupon.com",
    "https://www.walmart.com",
    "https://www.foursquare.com",
    "https://www.amazon.ca",
    "https://www.tiny.cc",
    "https://www.services.google.com",
    "https://www.xkcd.com",
    "https://www.target.com",
    "https://www.developers.facebook.com",
    "https://www.nginx.com",
    "https://www.canva.com",
    "https://www.s7.addthis.com",
    "https://www.elmundo.es",
    "https://www.i2.wp.com",
    "https://www.gizmodo.com",
    "https://www.expedia.com",
    "https://www.picasaweb.google.com",
    "https://www.money.cnn.com",
    "https://www.timesofindia.indiatimes.com",
    "https://www.yandex.ru",
    "https://www.vice.com",
    "https://www.de-de.facebook.com",
    "https://www.pastebin.com",
    "https://www.samsung.com",
    "https://www.rt.com",
    "https://www.ifttt.com",
    "https://www.dev.mysql.com",
    "https://www.giphy.com",
    "https://www.use.fontawesome.com",
    "https://www.houzz.com",
    "https://www.learningmanager.com"
    // You can continue to add the rest of the URLs here...
);


    public void crawlAll() {
        for (String url : urlsToCrawl) {
            crawl(url);
        }
    }

    public void crawl(String startUrl) {
        System.out.println("Starting crawl from: " + startUrl);

        WebDriver driver = null;
        try {
            driver = new ChromeDriver();
            driver.get(startUrl);

            Thread.sleep(2000); // Wait for page load

            String pageSource = driver.getPageSource();

            // Use Gemini to detect dark pattern
            boolean darkPatternDetected = geminiClient.isDarkPattern(pageSource);
            if (darkPatternDetected) {
                firebaseService.saveDetectionResult("CrawledPage", "Dark pattern detected on " + startUrl, "High");
                System.out.println("Dark pattern detected on: " + startUrl);
            } else {
                System.out.println("No dark pattern detected on: " + startUrl);
            }

            // Print all links on the page (optional)
            for (WebElement link : driver.findElements(By.tagName("a"))) {
                String url = link.getAttribute("href");
                if (url != null && (url.startsWith("http://") || url.startsWith("https://"))) {
                    System.out.println("Found link: " + url);
                }
            }

        } catch (Exception e) {
            System.err.println("Error during crawling: " + e.getMessage());
        } finally {
            if (driver != null) {
                driver.quit();
            }
            System.out.println("Crawling complete for: " + startUrl);
        }
    }
}
